- name: Install MongoDB
  shell: |
    amazon-linux-extras enable mongodb4.0
    yum install -y mongodb-org
  args:
    executable: /bin/bash

- name: Enable and start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
